JID3314-58 Subtask 2/2: Displaying Statistics at the Top of Each Report
waffy1901/JID-3314-CDC-Data-Reconciliation pull request #33
Opened 2024-02-14 04:54 UTC by waffy1901

2024-02-14 19:42 UTC, jonnamorrison approved these changes
great job!

2024-02-15 00:46 UTC, solomonmcharo28 commented on CDC-Data-Reconciliation-Frontend/src/components/Report.jsx
> +			const response = await fetch(`http://localhost:8000/report_statistics/${reportID}`)
may not want to hardcode the endpoint, could use a global variable to identify the beginning of the endpoint as its gonna change when everything goes live

2024-02-15 00:46 UTC, solomonmcharo28 commented on CDC-Data-Reconciliation-Frontend/src/components/Report.jsx
>      const csvData =
this variable is never used again

2024-02-15 00:50 UTC, Carson21 requested changes
Make sure to calculate the total statistics for the report.

2024-02-15 00:50 UTC, Carson21 commented on CDC-Data-Reconciliation-Frontend/src/components/Report.jsx
> +			{!showDiseaseSpecificStats ? (
showDiseaseSpecificStats is not a defined variable. I think you meant to use showDiseaseStats

2024-02-15 00:50 UTC, Carson21 commented on CDC-Data-Reconciliation-Frontend/src/components/Report.jsx
> +					<td>{statistics.TotalCases}</td>
Make sure to actually calculate the totals for the entire report. There does not exist TotalCases, TotalDuplicates, etc.. attributes on the statistics data. You will need to calculate this whenever you get the data back from the server. You can either calculate the total statistics for the report either server side using SQL or on the frontend.

2024-02-15 00:50 UTC, Carson21 commented on CDC-Data-Reconciliation-Frontend/src/components/Report.jsx
> +					{statistics.DiseaseStats.map((stat) => (
There does not exist a DiseaseStats attribute on the statistics data you get back from the API. you should just use statistics.map

2024-02-15 03:40 UTC, Carson21 approved these changes
Looks good now

2024-02-15 03:42 UTC, merged