Improve modal
waffy1901/JID-3314-CDC-Data-Reconciliation pull request #75
Opened 2024-03-28 19:39 UTC by solomonmcharo28

Set spacing between buttons and labels, 
Centered the file input prompter, 
Boldened the text of some of the values

2024-03-28 19:50 UTC, Carson21 reviewed
Can you use tailwindcss instead of setting style? For instance, line 104 in CreateReport.jsx can be `className="mr-4"` instead of `style={{ marginRight: 4px }}`

2024-03-28 19:58 UTC, jonnamorrison submitted a review, later dismissed
would mitigate the bolding of the Upload CSV and query specification labels, would bold create new report label and keep black, submit button should remain consistent with settings one

2024-03-28 20:10 UTC, Carson21 requested changes
Use tailwindcss instead of setting style directly

2024-03-28 20:12 UTC, p-zach commented
- Modal title should more clearly be a title (a little larger, black text, otherwise it looks like a button with the blue text)
- It still looks a little messy; making it look more like the settings page would probably help. Input forms don't usually have centered text, I think the text should be left-aligned
- None of the other submit buttons in the app have an icon, should probably remove the check mark for uniformity

2024-03-28 20:27 UTC, waffy1901 commented on CDC-Data-Reconciliation-Frontend/src/components/CreateReport.jsx
> +              <input type='checkbox' checked={isCDCFilter} onChange={handleCDCFilterChange} style={{ marginRight: '4px'}} />
change style={{ marginRight: '4px'}} to className="mr-4"

2024-03-29 03:22 UTC, Carson21 approved these changes
I think it looks way better than before. I think maybe just round the edges a little bit of the background and it will look better.

2024-03-29 03:31 UTC, jonnamorrison approved these changes

2024-03-29 03:31 UTC, merged